### ISSUE TITLE
yarn bootstrap.  Unsupported option name ("--mutex")

### ISSUE THREAD

**Issue by flavinlouise** [lifinance/jumper.exchange#516]
cli: yarn bootstrap
lerna notice cli v6.5.1
lerna info versioning independent
lerna info bootstrap root only
Unknown Syntax Error: Unsupported option name ("--mutex").

MacOS 13.3.1 (22E261)
yarn 3.5.0

**Comment by dennyscode** [comment]
Thanks for opening that issue @flavinlouise , we will be working on it!
As a workaround, as of now, it is best to just install the dependencies in the packages folders "dapp" and "shared" manually.

**Comment by Addminus** [comment]
Sorry for closing. Should remain open until fixed

**Comment by chybisov** [comment]
You don't need to run `yarn bootstrap` here. Just `yarn` will be enough.

**Comment by Addminus** [comment]
Updated readme on how to use this repo
