### ISSUE TITLE
Jumper on Shibarium

### ISSUE THREAD

**Issue by YungSB** [lifinance/jumper.exchange#786]
I would love to see Jumper add Shibarium support. Shibarium is currently in it's early stages and only has the main bridge from the Shib team into Shibarium, which is only through Ethereum. Jumper integrating shibarium would bring a whole new way of users to lifi while also giving users more options to bridge into shibarium because not many people know how to.

**Comment by chybisov** [comment]
We appreciate your interest in the project and we are constantly adding new chains! Stay tuned! 🙂
