### ISSUE TITLE
Finalizing bridge-swap error

### ISSUE THREAD

**Issue by tartsmart** [lifinance/jumper.exchange#806]
Whenever bridging from any network to Polygon, meaning there is going to be a swap at the end of all transactions from native token of the sender network (ETH) to MATIC, if there's barely enough gas on the destination chain (Polygon) and the swap fails, and then you cancel the pending transaction by doing a tx with the same Nonce parameter, the failed swap just remains as processing on Jumper forever.

It just says "Waiting for swap transaction", but I already swapped manually after canceling the pending one.

There at least needs to be an ability to cancel the last part of the bridge. It's just forever in progress and there is nothing I can press on the UI to cancel it or to let it know that I finished the swap manually.

**Comment by chybisov** [comment]
@tartsmart Hey, thank you for filing an issue. When canceling the transaction, did you have the Jumper page open?

**Comment by Addminus** [comment]
@tartsmart Please check if your issue is still valid. We are happy to help, provided you give us the info we need to help you :)

If not, we will consider the issue as resolved and close it.

**Comment by ITNAAG** [comment]
Zksycn to Arbitrum  brige used but not revived eth on arbitrum chain
transition tx- 0x4eca1c8da4c8665456a32fef37e9f335ba9d3fa49ace3ef777c2701316f7f8d3
<img width="1397" alt="Screenshot 2024-06-01 at 6 57 21 AM" src="https://github.com/lifinance/jumper.exchange/assets/39451611/0d23b308-5fd9-4dce-b268-25d47105d8ca">
