### ISSUE TITLE
(smol UI bug i think) After performing the specified steps, the hamburger menu shifts to the left side of the UI.

### ISSUE THREAD

**Issue by makkarankush68** [lifinance/jumper.exchange#896]
### Steps to Reproduce in video :

https://github.com/lifinance/jumper.exchange/assets/97383407/87258b28-ff41-44df-b09c-6ccffa408dde

#### using brave & Windows 11 rn.

**Comment by tcheee** [comment]
Hey @makkarankush68, thanks for the bug report. We'll tackle this UI issue. I close this issue as I have moved your report into our workflow. 
Thanks
